// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Transport.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CostoDeEntregaPorTipoDeTransporteFeature : object, Xunit.IClassFixture<CostoDeEntregaPorTipoDeTransporteFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CostoEntrega.feature"
#line hidden
        
        public CostoDeEntregaPorTipoDeTransporteFeature(CostoDeEntregaPorTipoDeTransporteFeature.FixtureData fixtureData, Transport_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("es"), "Features", "Costo de entrega por tipo de transporte", "  Para calcular costos de envío\r\n  Como planificador logístico\r\n  Quiero conocer " +
                    "el costo por distancia según el transporte", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Calcular costo directo por tipo")]
        [Xunit.TraitAttribute("FeatureTitle", "Costo de entrega por tipo de transporte")]
        [Xunit.TraitAttribute("Description", "Calcular costo directo por tipo")]
        [Xunit.InlineDataAttribute("Airbus", "10", "30", new string[0])]
        [Xunit.InlineDataAttribute("Truck", "20", "20", new string[0])]
        [Xunit.InlineDataAttribute("Ship", "20", "10", new string[0])]
        public void CalcularCostoDirectoPorTipo(string tipo, string distancia, string costo, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tipo", tipo);
            argumentsOfScenario.Add("distancia", distancia);
            argumentsOfScenario.Add("costo", costo);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calcular costo directo por tipo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given(string.Format("un transporte \"{0}\"", tipo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 9
    testRunner.When(string.Format("calculo el costo para {0} millas", distancia), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line hidden
#line 10
    testRunner.Then(string.Format("el costo debe ser {0}", costo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Calcular costo usando fábrica")]
        [Xunit.TraitAttribute("FeatureTitle", "Costo de entrega por tipo de transporte")]
        [Xunit.TraitAttribute("Description", "Calcular costo usando fábrica")]
        [Xunit.InlineDataAttribute("TruckFactory", "20", "20", new string[0])]
        [Xunit.InlineDataAttribute("ShipFactory", "20", "10", new string[0])]
        public void CalcularCostoUsandoFabrica(string factory, string distancia, string costo, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("factory", factory);
            argumentsOfScenario.Add("distancia", distancia);
            argumentsOfScenario.Add("costo", costo);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calcular costo usando fábrica", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
    testRunner.Given(string.Format("una fábrica de transporte \"{0}\"", factory), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 20
    testRunner.When(string.Format("creo el transporte y calculo el costo para {0} millas", distancia), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line hidden
#line 21
    testRunner.Then(string.Format("el costo debe ser {0}", costo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CostoDeEntregaPorTipoDeTransporteFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CostoDeEntregaPorTipoDeTransporteFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
